# Generated by Django 3.1.3 on 2020-11-26 14:19

import API.utils
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ASRInputSound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='ASR_Input/')),
            ],
        ),
        migrations.CreateModel(
            name='ASRText',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('text_content', models.TextField(blank=True, null=True)),
                ('inference_time', models.CharField(blank=True, max_length=255, null=True)),
                ('audio_join_Transformed', models.FileField(blank=True, null=True, upload_to=API.utils.get_asr_media)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ASRText',
                'verbose_name_plural': 'ASRTexts',
            },
        ),
        migrations.CreateModel(
            name='TTSSound',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('text_content', models.TextField(blank=True, null=True)),
                ('audio_join', models.FileField(blank=True, null=True, upload_to=API.utils.get_tts_media)),
                ('inference_time', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
